BancoApp/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using BancoApp.Models;
using System.Data;

namespace BancoApp.Controllers
{
    public class BancoController : Controller
    {
        
        // GET: Banco
        [HttpGet]
        public ActionResult Index()
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;
            MySqlConnection conn = context.GetConnection();
            
            conn.Open();
            DataTable dt = new DataTable();
            string sqlquery = "SELECT * FROM Banco";
            MySqlDataAdapter sda = new MySqlDataAdapter(sqlquery, conn);
            sda.Fill(dt);

            return View(dt);
        }

       

        // GET: Banco/Details/5
        public ActionResult Details(int id)
        {
            BancoModel bancoModel = new BancoModel();
            DataTable dt = new DataTable();

            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();
            conn.Open();
            string sqlquery = "SELECT * FROM Banco WHERE idBanco = @IdBanco";
            MySqlDataAdapter sda = new MySqlDataAdapter(sqlquery, conn);
            sda.SelectCommand.Parameters.AddWithValue("@IdBanco", id);
            sda.Fill(dt);
            if (dt.Rows.Count == 1)
            {
                bancoModel.IdBanco = Convert.ToInt32(dt.Rows[0][0].ToString());
                bancoModel.Nombre = dt.Rows[0][1].ToString();
                bancoModel.Direccion = dt.Rows[0][2].ToString();
                bancoModel.FechaRegistro = (System.DateTime)dt.Rows[0][3];

                // get list sucursales
                DataTable dts = new DataTable();
                string sqlquery_s = "SELECT * FROM Sucursal WHERE Banco_idBanco = @IdBanco";
                MySqlCommand cmd = new MySqlCommand(sqlquery_s, conn);
                cmd.Parameters.AddWithValue("@IdBanco", id);
                MySqlDataReader sdr = cmd.ExecuteReader();

                List<SucursalModel> list = new List<SucursalModel>();
                while (sdr.Read())
                {
                    list.Add(new SucursalModel()
                    {
                        IdSucursal = Convert.ToInt32(sdr["IdSucursal"]),
                        Nombre = sdr["Nombre"].ToString(),
                        Direccion = sdr["Direccion"].ToString(),
                        FechaRegistro = (System.DateTime) sdr["FechaRegistro"],
                        IdBanco = Convert.ToInt32(sdr["Banco_idBanco"].ToString()),
                    });
                }
                ViewBag.sucursales = list;

                return View(bancoModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Banco/Create
        public ActionResult Create()
        {
            return View(new BancoModel());
        }

        // POST: Banco/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BancoModel bancoModel)
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();

            conn.Open();
            string sqlquery = "INSERT Into Banco (nombre, direccion, fechaRegistro)VALUES (@Nombre, @Direccion, @FechaRegistro)";
            MySqlCommand cmd = new MySqlCommand(sqlquery, conn);
            //cmd.Parameters.AddWithValue("@IdBanco", bancoModel.IdBanco);
            cmd.Parameters.AddWithValue("@Nombre", bancoModel.Nombre);
            cmd.Parameters.AddWithValue("@Direccion", bancoModel.Direccion);
            cmd.Parameters.AddWithValue("@FechaRegistro", bancoModel.FechaRegistro);
            cmd.ExecuteNonQuery();   
            conn.Close();
            return RedirectToAction("Index");
        }

        // GET: Banco/Edit/5
        public ActionResult Edit(int id)
        {
            BancoModel bancoModel = new BancoModel();
            DataTable dt = new DataTable();

            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();
            conn.Open();
            string sqlquery = "SELECT * FROM Banco WHERE idBanco = @IdBanco";
            MySqlDataAdapter sda = new MySqlDataAdapter(sqlquery, conn);
            sda.SelectCommand.Parameters.AddWithValue("@IdBanco", id);
            sda.Fill(dt);
            if (dt.Rows.Count == 1){
                bancoModel.IdBanco = Convert.ToInt32(dt.Rows[0][0].ToString());
                bancoModel.Nombre = dt.Rows[0][1].ToString();
                bancoModel.Direccion = dt.Rows[0][2].ToString();
                bancoModel.FechaRegistro = (System.DateTime) dt.Rows[0][3];
                return View(bancoModel);
            }
            else {
                return RedirectToAction("Index");
            }

        }

        // POST: Banco/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BancoModel bancoModel)
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();

            conn.Open();
            string sqlquery = "Update Banco SET Nombre=@Nombre, Direccion=@Direccion, FechaRegistro=@FechaRegistro WHERE idBanco=@IdBanco";
            MySqlCommand cmd = new MySqlCommand(sqlquery, conn);            
            cmd.Parameters.AddWithValue("@IdBanco", bancoModel.IdBanco);
            cmd.Parameters.AddWithValue("@Nombre", bancoModel.Nombre);
            cmd.Parameters.AddWithValue("@Direccion", bancoModel.Direccion);
            cmd.Parameters.AddWithValue("@FechaRegistro", bancoModel.FechaRegistro);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }

        // GET: Banco/Delete/5
        public ActionResult Delete(int id)
        {

            BancoModel bancoModel = new BancoModel();
            DataTable dt = new DataTable();

            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();
            conn.Open();
            string sqlquery = "SELECT * FROM Banco WHERE idBanco = @IdBanco";
            MySqlDataAdapter sda = new MySqlDataAdapter(sqlquery, conn);
            sda.SelectCommand.Parameters.AddWithValue("@IdBanco", id);
            sda.Fill(dt);
            if (dt.Rows.Count == 1)
            {
                bancoModel.IdBanco = Convert.ToInt32(dt.Rows[0][0].ToString());
                bancoModel.Nombre = dt.Rows[0][1].ToString();
                bancoModel.Direccion = dt.Rows[0][2].ToString();
                bancoModel.FechaRegistro = (System.DateTime)dt.Rows[0][3];
                return View(bancoModel);
            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        // POST: Banco/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();

            conn.Open();
            string sqlquery = "DELETE FROM Banco WHERE idBanco=@IdBanco";
            MySqlCommand cmd = new MySqlCommand(sqlquery, conn);
            cmd.Parameters.AddWithValue("@IdBanco", id);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
    }
}

BancoApp/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BancoApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace BancoApp.Controllers
{
    public class SucursalController : Controller
    {

        // GET: Sucursal
        [HttpGet]
        public ActionResult Index()
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;
            MySqlConnection conn = context.GetConnection();

            conn.Open();
            DataTable dt = new DataTable();
            string sqlquery = "SELECT * FROM Sucursal";
            MySqlDataAdapter sda = new MySqlDataAdapter(sqlquery, conn);
            sda.Fill(dt);

            return View(dt);
        }

        // GET: Sucursal/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sucursal/Create
        public ActionResult Create(int id)
        {
            return View(new SucursalModel());
        }

        // POST: Sucursal/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.SucursalModel sucursalModel, int id)
        {
            BancoAppContext context = HttpContext.RequestServices.GetService(typeof(BancoApp.Models.BancoAppContext)) as BancoAppContext;

            MySqlConnection conn = context.GetConnection();

            conn.Open();
            string sqlquery = "INSERT Into Sucursal (nombre, direccion, fechaRegistro, Banco_idBanco) VALUES ( @Nombre, @Direccion, @FechaRegistro, @Banco_idBanco)";
            MySqlCommand cmd = new MySqlCommand(sqlquery, conn);
            //cmd.Parameters.AddWithValue("@IdSucursal", sucursalModel.IdSucursal);
            cmd.Parameters.AddWithValue("@Nombre", sucursalModel.Nombre);
            cmd.Parameters.AddWithValue("@Direccion", sucursalModel.Direccion);
            cmd.Parameters.AddWithValue("@FechaRegistro", sucursalModel.FechaRegistro);
            cmd.Parameters.AddWithValue("@Banco_idBanco", id);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Details", "Banco", new {@id = id});

        }

        // GET: Sucursal/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sucursal/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Sucursal/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sucursal/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BancoApp/Views/Banco/Create.cshtml
@model BancoApp.Models.BancoModel

@{
    ViewData["Title"] = "Create";
}

<h2>Crear nuevo Banco</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!-- <div class="form-group">
                <label asp-for="IdBanco" class="control-label"></label>
                <input asp-for="IdBanco" class="form-control" />
                <span asp-validation-for="IdBanco" class="text-danger"></span>
            </div> -->
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a Lista de Bancos</a>
</div>

BancoApp/Views/Banco/Delete.cshtml
@model BancoApp.Models.BancoModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Eliminar</h2>

<h3>Estas seguro que quieres eliminar este Banco?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdBanco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdBanco)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

BancoApp/Views/Banco/Details.cshtml
@model BancoApp.Models.BancoModel

@{
    ViewData["Title"] = "Details";
}

<h2>Detalles del Banco</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdBanco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdBanco)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Regresar</a>
</div>

<hr />
<h1>Sucursales</h1>

<table class="table table-responsive table-bordered table-striped">
    <tr>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>Fecha Registro</th>
        <th>Operaciones</th>

    </tr>
    @foreach (var sucursal in ViewBag.sucursales)
    {
        <tr>
            <td>@sucursal.Nombre</td>
            <td>@sucursal.Direccion</td>
            <td>@sucursal.FechaRegistro</td>
           <td>
                <a class="btn btn-default btn-xs" href="#">Editar</a>
                <a class="btn btn-default btn-xs" href="#">Eliminar</a>
        </td>
        </tr>
    }
</table>



<a class="btn btn-primary btn-xs" href="@Url.Action("Create", "Sucursal", new {@id = @Model.IdBanco})">Crear nueva sucursal</a>

BancoApp/Views/Banco/Edit.cshtml
@model BancoApp.Models.BancoModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => Model.IdBanco)

            <!--
    <div class="form-group">
        <label asp-for="IdBanco" class="control-label"></label>
        <input asp-for="IdBanco" class="form-control" />
        <span asp-validation-for="IdBanco" class="text-danger"></span>
    </div>
        -->
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

BancoApp/Views/Banco/Index.cshtml
@model System.Data.DataTable
@{
    ViewData["Title"] = "Index";
}

<h1>Bancos </h1>
<table class="table table-responsive table-bordered table-striped" >
    <tr>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>Fecha Registro</th>
        <th>Operaciones</th>

    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++) {
    <tr>
        <td>@Model.Rows[i][1]</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][3]</td>
        <td>
            <a class="btn btn-default btn-xs" href="@Url.Action("Details", "Banco", new {@id=@Model.Rows[i][0]})">Detalle</a>
            <a class="btn btn-default btn-xs" href="@Url.Action("Edit", "Banco", new {@id=@Model.Rows[i][0]})">Editar</a>
            <a class="btn btn-default btn-xs" href="@Url.Action("Delete", "Banco", new {@id=@Model.Rows[i][0]})">Eliminar</a>
        </td>
    </tr>
    }
</table>

<a class="btn btn-primary btn-xs" href="@Url.Action("Create", "Banco")">Crear Nuevo Banco</a>